import Foundation

// MARK: - Fixtures

/// Two real archives, generated by Python's `zipfile` and embedded as base64.
///
/// They are produced outside Swift on purpose. A fixture the code under test
/// could itself have written is a fixture that can agree with the code about a
/// bug; these bytes, and the entry sizes and CRC-32 values recorded below, come
/// from an independent implementation, so agreement between the two means
/// something.
///
/// The synthetic archive is built to reach every branch of the DEFLATE decoder
/// rather than to look like a document:
///
/// | entry        | what it exercises                                              |
/// |--------------|----------------------------------------------------------------|
/// | `stored.txt` | ZIP method 0 — no DEFLATE stream at all                        |
/// | `tiny.txt`   | a one-byte payload under DEFLATE                               |
/// | `repeat.txt` | 18 000 bytes to 117 — long back-references, large distance set |
/// | `random.bin` | incompressible, so zlib emits a *stored DEFLATE block* (type 00) |
/// | `allbytes.bin` | all 256 literal codes and the long code-length alphabet      |
/// | `run.bin`    | 20 000 identical bytes to 37 — self-overlapping copies         |
///
/// `random.bin` compresses to 4 005 bytes from 4 000, which is the case real
/// `.docx` files hit constantly because of embedded PNG and JPEG data.
enum Fixtures {

    struct Entry {
        let name: String
        let method: Int
        let uncompressedSize: Int
        let crc32: UInt32
    }

    static let synthetic: [UInt8] = decode(
        "UEsDBBQAAAAAAABgQ12rdjcPJAAAACQAAAAKAAAAc3RvcmVkLnR4dEhlbGxvLCBzdG9yZWQgZW50cnkgLSB1bmNv" +
        "bXByZXNzZWQuClBLAwQUAAAACAAAYENdi57Z0wMAAAABAAAACAAAAHRpbnkudHh0cwQAUEsDBBQAAAAIAABgQ10S" +
        "f38cdQAAAFBGAAAKAAAAcmVwZWF0LnR4dO3K2xGCMBQA0VZuBfSkEARRoiHBR/U6VuHH+dzZU6cU9zb3SxxLfqwx" +
        "5mec2/W2Rd5Tifrdl8P7FUM+db+CYRiGYRiGYRiGYRiGYRiGYRiGYRiGYRiGYRiGYRiGYRiGYRiGYRiGYRiGYRiG" +
        "YRiGYRiG/xJ/AFBLAwQUAAAACAAAYENdximyHKUPAACgDwAACgAAAHJhbmRvbS5iaW4BoA9f8Bjhq5nh80UXquqN" +
        "Rub0fTlhbQpXZcs4RwhpxP9ivm+Xths/NgE2w7TlOqsZ2BTanYmVGREaMmNirUVmUreLqjvZXuQrKSgoAQH8FxOc" +
        "Jv2BIt6+MLniIrj19dRRZnQ9XvdSLzUiA4BW1dytMpTplYig9mX5olGvh80sc8+PLmjzpQA4Wf8UG+ux+/grbvJl" +
        "MfUWHV8HaH0SG7Q0e2Dvqdct1xlbaNgnnF+M8XLYh+J3FR3O6m5jltZ17EH0JOMdilmmjrynENPROaMl0xY29FMt" +
        "yylUtqyDKxNRimrXUVVTU1WmSAZCcg6Gj1e0NOsXq184x5Ev+xqbnepNT+XC6X5brf8VPG/ca+aRb4rzKN1REqac" +
        "OkX0ewZNadxFgD/VpOq4GUcu6XpzChFXs1/et1zvhdm7PkI23hwaiQIPqmaKWZb0aro3YriCBzo+D3TgJ91e/g2O" +
        "oVOPMga42LVgPfmWTgtKF1R1oOmHqEXMbxL4EM/YOavZBU3eCSVTX31TYtsEl2SLqPur3y9RM9nkdUYVnpUKh3sF" +
        "IFb6jXyxIygnjPEpGY/k7rxuHK+iQL9YVWUcp2IHFO1HmKG1NercYKYPDWnhQ6oAb6ofJuuTtnLPcAMWC3Qpqxr0" +
        "Ic9W/NNCuWFsZeeDRS/PwjFjA6T+A7zqGp0Gp5rgADw4vAtveOnG2wf6F7HL+QAhs4dxfM7/lXxq9pcxVa7weP6s" +
        "0whP7jbXbngyNzZvLEBQT9e6YznJzoyxjykjWB2wYSqyNZKpXM3CVFFS6nOJ7KG9rfkXucZp5+5EHAcV9/2LkhT2" +
        "QnXzdLvUVwcfphRQ7hGRwcwz5/X08hgQUmRl+JXT4W+nekHJlgo+77b+A6S5V3fZz+vWFY3in7HtgAG1sZ5mwGiE" +
        "F9o/A2X+xNHt/FxCjTdxgH+GxIf+SexbGbj8Il0NeOPugQYlWfq3I7TZjPnM9Pdz9A9MiTgDAM7nk8ylE0MdB7qw" +
        "M80edY5lW0V/YSQAaDqQN6McjWotdJShRr2lrvA5n+2CE3JQB0dn5EvItkv6J6/w9Ci1BrD1bQY0EE9ymlTj+ukF" +
        "rarKyQyZ/wQd9VGRBiUHRg0PJcCo129BIuLaXyexxFOAwyteLXus0jdSlbgYqw/fhM79rNKZVB5aAeriQPzaqjZP" +
        "be1wL4ZccRlB1HQWRJXJDDQH1KT91wsbdTkdfSHXXAG7Ege6Wa0O7ybTZkYSOTMrRxGRSSBkLDzSrrAtn5RSQHHI" +
        "G84gIjyOrxpaHoo/J2by70rmP80jsrRvkcqFxRcW6sGCNSmVCWCgfjW4MEo83QiSrAOdg1/DFDzv8JsM8GiFrw8k" +
        "IsVZN0moPO42lKlkXn8Gwy+VDLVihSHC30jTpdLcq6E/XOlkmmaewA0tZUGknmk3YHu4JYD5jC1nVxF8161cyLJh" +
        "FcciyN4YuubJs6KeQg9nbn9ow5+x/a4lEXJXJhTReSdWzfl4pGYZp08t3pAUTgPM/NbDZJb/RNXY+Bp8LcKak2wk" +
        "2CkF2QYq7xoOW3sN2XFJncqx8fDwR3kuGd5dDXeDCBVT5X2qN5vexyeFT5RNlbkJ0W+D1asXA3J1dEM1XUOOekiv" +
        "sqkmpb++2ihudII8aesVlG02ErAyPZwGb6I41ccprdRBwgR3FMZUo57O7M0h9DBJE9pRN8o9mHvGOOuhiTNDI/u5" +
        "jX2XGEBUMZzYyg+crNe66wR4r1Elap4sUtSxUpuxpdr0klnUiJurpj5nWsqWDDcNhV7Uf20RehhU2cgX4i9isDwB" +
        "nugsxt+2aUVIZRve0Q4tOzRnkNGJxe4Lqg/VDHbpl64oWRUuXRGX+s53LzaCjV5O3yE7GVAhQQDYKhnrBO4g9eEP" +
        "GTurmSst3l0NCtPfJwdcBgbXTPXQrJX9jYq4t7J60Het7137oICpLekf8w12Iz/1S68TGnF9AJ1zHYXbX3H8z9tb" +
        "A0tWJcSDpSwlaKd2+bAlr0QJdGo+qBhZWi87ICc3IZp58UluncSGraLaX81OCiassgdHgRR15U9pqA7Ia+kMEwwR" +
        "z9pISS3KOYLWxu1+DzUrZ7PU0FU85G9iMFjEFre3FqcrQjTAFX7PI3WYtMQ+YktAAq3GcqXbToM2dXkg9I49UPFY" +
        "B2aB+LzQc3UXcvfca8h7L1Efm1iEXJ76vJS5DrAD+PnRJEOA/H9+UiDVsk4m+OknwNDf802H1H0nsTFBwx6xy1/U" +
        "KVof+x4VOl3SzO7/p5MrgrRFM+n2kSuENmUubPV8JC6ubnGdcJjesf0//EwFPzHMq1wySH4kUuVNQ5kOHahdRmP1" +
        "WOH2M7ONEfol4XJ8udRi5LDFvVQoz44NT5KR2q3UwofWgC9INLsk8DX6gjNUwvrrzJuFQ34llsYiyc06uygBbaTV" +
        "uKn7kMC5xiozS2QASjJ9EuzqWO2dLV3TSPRdh2z06QoRlE0kaOC0U8cdc8JKmA/ovO9xfHE/DztYt/I8CiPloEs0" +
        "WDrTg1H1usSgKLLwlFUeJWqhZArFYL1jBkWVb7agAAirn3RGj6kWlKVuBzQaFOL7CkvgsBfUUNRdsGPGoVpboxOK" +
        "9qww1V1p177CQ8+ywR5g1Hm1TIF9AguItbAivJEsx8iE8jKih4NnUY0LxzMWF2Ws2NXMHhKXYn09cHEiFSglXqMv" +
        "Jmxy4/8Q4qh14o3jBLPnprwYL6ZStWMyHl/ZA4lhLUG+94StvYo0BR0R3knR41hLuEBrOKpUr7P5LU5p9pWeIlIr" +
        "jV8bFRz+D456kPnqwxUDzCojk4RpUrLJH9gbY42lPz5IxkzJB8qV+0AxOKgPpBj06S13aDMi1qEqcsoeyFvCsSZL" +
        "07NkZR8kINddKX5Pec+aCVMmLbO8sswNh59JPUNV5YkPVXncZPYOuVKHywaqGRh2Xy9gdWOPVMtfgVQyndnpu0NK" +
        "UKlWgvB5A2pA9aJizeBhlVDyIzrZJ9PgBiWwQTVhNqg7Erxx3O4yanoJJUws/Vn6pa6p1U70QAawNEclh7pMFkIH" +
        "Sxh3voXM2zL3hqWuljc3yoai2QafBu63AHbXs+i2KhyhfEDD1f2ZOAHrUvOTa5GqGytkkj7YxoUTXI1HBE3jXSbs" +
        "1eg1DVgwcquIkeGwqdnYlzcMT0d9A4n4Jr3DEwjP27twqEjfQFgGGXslg5j51EXqXOQ4YHga2W+UemqjfwgwXba7" +
        "dpdMl9eS1fhnjY5xBypIMZHXXs/sTUhaqcWVPRSJXvqK73a4awf4+Y0QHGvGnFDPJDHPzFhF3vRCvFe344ChW+LI" +
        "CSzkc19/wgz7U5XoconreZe7scu8C5gqCJnsXkR8VZhGOxBiys+jtKoz2BQbnw8hVDqBGYDP2AsoV5aUwaaGmbWp" +
        "QYfhZ5UnnBcGoyywIUwzirKxb1ZPeXVdkQvoQvmnsEK6mcp7pxSfRjLg3gW+DacdIiSHK57X0PLU1TT8q5vTkhDp" +
        "Dvx6Y3lR4em3ayI09pIKBi1/oRpITlbqt2FBk5tKdVBNwy9UFAlGVf4h3Ezrjt16oP7TblFbz5VdBguodyM0A3Nq" +
        "3MwXdZjU0qEUwwTyuvYsKbVGZyfkKSAPRjuwYHWgqtPgBQ5715BvBAOW5Jj9tXj+1NFkh8Y31eDv71lJYVuWXlw6" +
        "M7f5+dGxIZNV2qU1dZSBISAlipGH9jMyw38YwqFRnhFTMclM9J+OLGKGR8FRXXhGOD18FUHlFyWWXyodU6vj6LOm" +
        "Xo3yaP4uw0GUZbOQyorocPun1QyALPpT4OuyCqUnizWm8lHneRTl2izOJ+wkayNOnnTI7OpZoDtjM/lNCkAFikXw" +
        "Xv1WxfFAREb014xCom4DRl5otp7NrIz3CUonZzRIhWh3fJHY0hUxsC/KPIlXleYMmgSsj+noZl/9QVY4g1QYUtXW" +
        "y1s9QjSbR4O9kcXzvCFmFbyaqx/31n+ht1YvFUPx3a90f4/Fg6nkV1cVMfopEQLUHWySOaOqHgnL1jeYP9a7D8bC" +
        "ul61cwJsKyFXH4ccQFpv+Sru/JSxEA4FY3Zr0lgVf4DPPxFZKc4Lk89fEXerLebKLRCZCtPw0RMd9guhG2iJLRlO" +
        "e3c9nSUYRZmxDW8DzmuPIEP+nYYRwbKjWPoJJ5vsdEQwH3Hvqxvc/fLx6eTXcxy96yDYEQ5ptTlnQ0vsGfG4nN9d" +
        "apy6Hi9QSwpPy55sdbzZGo3+5xvM5XEyFIryTcNgymGeu3sx3NBo78Vx7z4ptc8lqqnC6HMU2gQbLjzne3TU+8cn" +
        "zeyRzc8J5E7X6BW6dd2TQt7fX980xufLhnNRaQasJbRikkq9JCyaUCMoAPhZi7O02iqVPvsf9V8rMWMGJbHsIicj" +
        "sHp7qprGNpOaps/+Z7iEvDtKu7sRtnV4f/Q4uui7At5pxQXfvk1WoQG7Z9ciIVL5KV5Nuqm8epRE0T0cl2notJ6e" +
        "njxdWcQ/u6VLXRddCmMwc97wA2xgT0Fijc/OhFJsDJ/yLln2HUeBeE6dv3TZuL2goWpNHQadcmQ1Hj7ty3VSdOmO" +
        "Re3RsrNQseubBXEDmWaQB5tujC28aFjVfxCAsKPKtVFdW76gNwDogJBYlAIiWhfpisCe1EMTXvc6xKeZTUUjZPK6" +
        "U/8jw28xEks0JDLPzgmXNboFNKdY+EuvGTBcgjHw69nT8hhVxZoiZuh8XNvh+TaoOGF05lQDe2Aby88N5QGWDO7F" +
        "3kvnpC1S7vi54igfCIjG0A4tR50F+XGhQ8ba9WtHduOp0giLnVAwbUKOzT06bClfgHfj56HHBVxaMnm9HKpdEb7X" +
        "o5XEX9eSpC5cS7wB1E1U4jp4en06oDS2R8zdUK1oZHLHE/yLh94w8TRAdPkF+sWill+Ui3bjyn5e5hgyT29s0cTb" +
        "IadQX+GeCfBPVASqSLVOfkZSScP8EGx3ySFfRuHEA24VDoogXifYyDVFBSJbKNpJtkUL/eGhdwjFXxb53cShcZzB" +
        "oUcT3HIHNmtrKP65/4Swb4Xbqc93mFf6EJ64C7U1+Zz2S1LLEnGFTDGP8+IrC4HELVzwrRnqiO1HZAoZzFeEmTVx" +
        "sNVZCA1aYWCBesGv3tnjMWcpgMaeRwmpPZcHw7cfCZH5qnsJ4YlPQNMo5QlbFo0m0RPP5sgViGCChYxC0O9ckHOS" +
        "HdmcYp6hY9Ys8+FvkxrKQteFlcIEwuEiBf1vBRmolzVbnqV7cRq/hc8GnAgsMDS99p6Ik910vsl0DTo2JM/UMdKK" +
        "cAKk7KU7dr3FqHhxzgJ4RKEhbiEKk7mA/R4v5xxLrKyVCfC+MK9eHWhVcWIKUvHHaaiNGROVzmqpHwJRAcKFjpg+" +
        "s7m4TtMjRkHdpexNiTnoSE0o7J0IwXil2Wy7ORlQSwMEFAAAAAgAAGBDXS3Hyk8rAQAAAAwAAAwAAABhbGxieXRl" +
        "cy5iaW5jYGRiZmFlY+fg5OLm4eXjFxAUEhYRFROXkJSSlpGVk1dQVFJWUVVT19DU0tbR1dM3MDQyNjE1M7ewtLK2" +
        "sbWzd3B0cnZxdXP38PTy9vH18w8IDAoOCQ0Lj4iMio6JjYtPSExKTklNS8/IzMrOyc3LLygsKi4pLSuvqKyqrqmt" +
        "q29obGpuaW1r7+js6u7p7eufMHHS5ClTp02fMXPW7Dlz581fsHDR4iVLly1fsXLV6jVr163fsHHT5i1bt23fsXPX" +
        "7j179+0/cPDQ4SNHjx0/cfLU6TNnz52/cPHS5StXr12/cfPW7Tt3791/8PDR4ydPnz1/8fLV6zdv373/8PHT5y9f" +
        "v33/8fPX7z9///1nGPX/qP9H/T/q/1H/j/p/1P+j/h/1/6j/R5D/AVBLAwQUAAAACAAAYENd8CRT8yUAAAAgTgAA" +
        "BwAAAHJ1bi5iaW7twTEBAAAAwqD+VZbSGh5AAQAAAAAAAAAAAAAAAAAAAAAAAPBgUEsBAhQDFAAAAAAAAGBDXat2" +
        "Nw8kAAAAJAAAAAoAAAAAAAAAAAAAAKQBAAAAAHN0b3JlZC50eHRQSwECFAMUAAAACAAAYENdi57Z0wMAAAABAAAA" +
        "CAAAAAAAAAAAAAAApAFMAAAAdGlueS50eHRQSwECFAMUAAAACAAAYENdEn9/HHUAAABQRgAACgAAAAAAAAAAAAAA" +
        "pAF1AAAAcmVwZWF0LnR4dFBLAQIUAxQAAAAIAABgQ13GKbIcpQ8AAKAPAAAKAAAAAAAAAAAAAACkARIBAAByYW5k" +
        "b20uYmluUEsBAhQDFAAAAAgAAGBDXS3Hyk8rAQAAAAwAAAwAAAAAAAAAAAAAAKQB3xAAAGFsbGJ5dGVzLmJpblBL" +
        "AQIUAxQAAAAIAABgQ13wJFPzJQAAACBOAAAHAAAAAAAAAAAAAACkATQSAABydW4uYmluUEsFBgAAAAAGAAYATQEA" +
        "AH4SAAAAAA=="
    )

    static let syntheticEntries: [Entry] = [
        Entry(name: "stored.txt", method: 0, uncompressedSize: 36, crc32: 0x0f3776ab),
        Entry(name: "tiny.txt", method: 8, uncompressedSize: 1, crc32: 0xd3d99e8b),
        Entry(name: "repeat.txt", method: 8, uncompressedSize: 18000, crc32: 0x1c7f7f12),
        Entry(name: "random.bin", method: 8, uncompressedSize: 4000, crc32: 0x1cb229c6),
        Entry(name: "allbytes.bin", method: 8, uncompressedSize: 3072, crc32: 0x4fcac72d),
        Entry(name: "run.bin", method: 8, uncompressedSize: 20000, crc32: 0xf35324f0),
    ]

    /// A minimal but structurally valid `.docx`: the three parts an OPC package
    /// needs, with the real ECMA-376 content types and relationship types.
    static let minimalDocx: [UInt8] = decode(
        "UEsDBBQAAAAIAMcCQ13JTxqw6wAAAK4BAAATAAAAW0NvbnRlbnRfVHlwZXNdLnhtbH1QvU7DMBDeeQrLK4odGBBC" +
        "STrwMwJDeYCTfUks7LPlc0v79jht6YAK4933q69b7YIXW8zsIvXyRrVSIJloHU29/Fi/NPdScAGy4CNhL/fIcjVc" +
        "det9QhZVTNzLuZT0oDWbGQOwigmpImPMAUo986QTmE+YUN+27Z02kQpSacriIYfuCUfY+CKed/V9LJLRsxSPR+KS" +
        "1UtIyTsDpeJ6S/ZXSnNKUFV54PDsEl9XgtQXExbk74CT7q0uk51F8Q65vEKoLP0Vs9U2mk2oSvW/zYWecRydwbN+" +
        "cUs5GmSukwevzkgARz/99WHu4RtQSwMEFAAAAAgAxwJDXbmBRHGwAAAAKgEAAAsAAABfcmVscy8ucmVsc43POw7C" +
        "MAwG4J1TRN5pWgaEUJMuCKkrKgeIEjeNaB5KwqO3JwMDIAZG278/y233sDO5YUzGOwZNVQNBJ70yTjM4D8f1DkjK" +
        "wikxe4cMFkzQ8VV7wlnkspMmExIpiEsMppzDntIkJ7QiVT6gK5PRRytyKaOmQciL0Eg3db2l8d0A/mGSXjGIvWqA" +
        "DEvAf2w/jkbiwcurRZd/nPhKFFlEjZnB3UdF1atdFRYob+nHi/wJUEsDBBQAAAAIAMcCQ123VG/YUAEAAGYCAAAR" +
        "AAAAd29yZC9kb2N1bWVudC54bWyFUstqwzAQvPcrhO61bJO2wcQO9FB6KQSSXnpT7LVlkCWx2sRNv77yI49CIZeV" +
        "Znc0ml1ptf7uNDsC+taanCdRzBmY0lataXL+uXt7XHLmSZpKamsg5yfwfF08rPqssuWhA0MsKBif9TlXRC4TwpcK" +
        "Oukj68CEWm2xkxQgNqK3WDm0JXgfLui0SOP4WXSyNbwIkntbnYbVjWGD47KlkwbWZ0epc/4OcrCWcFGsxIUzBiq+" +
        "wLSkhjyNVZw4F8WJOx3ZiyH6n7Nwupgl5/rYVuadLEPTDsEDHoEXr1ZXTBJLUuYoYn/uuvjY6NAQw4NhsiZA1lJ0" +
        "xxQVO9VixZxE2aB06v8DHkqap9JsB+th6EmaLsKj9ZkK+6dl2IuJ8CExZMm6kF9MFGwbRVe4t0S2u2IN9U1VhVED" +
        "5vwlHWFtLd3A5kAjjOexna2J8yuK6w8pfgFQSwECFAMUAAAACADHAkNdyU8asOsAAACuAQAAEwAAAAAAAAAAAAAA" +
        "gAEAAAAAW0NvbnRlbnRfVHlwZXNdLnhtbFBLAQIUAxQAAAAIAMcCQ125gURxsAAAACoBAAALAAAAAAAAAAAAAACA" +
        "ARwBAABfcmVscy8ucmVsc1BLAQIUAxQAAAAIAMcCQ123VG/YUAEAAGYCAAARAAAAAAAAAAAAAACAAfUBAAB3b3Jk" +
        "L2RvY3VtZW50LnhtbFBLBQYAAAAAAwADALkAAAB0AwAAAAA="
    )

    static let minimalDocxEntries: [Entry] = [
        Entry(name: "[Content_Types].xml", method: 8, uncompressedSize: 430, crc32: 0xb01a4fc9),
        Entry(name: "_rels/.rels", method: 8, uncompressedSize: 298, crc32: 0x714481b9),
        Entry(name: "word/document.xml", method: 8, uncompressedSize: 614, crc32: 0xd86f54b7),
    ]

    /// The document part of `minimalDocx`, exactly. Asserted as a string so a
    /// decoding error cannot hide inside a digest comparison.
    static let minimalDocxDocumentXML =
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n"
        + "<w:document xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\">"
        + "<w:body>"
        + "<w:p><w:pPr><w:pStyle w:val=\"Heading1\"/></w:pPr><w:r><w:t>Zenith</w:t></w:r></w:p>"
        + "<w:p><w:r><w:rPr><w:b/><w:sz w:val=\"24\"/></w:rPr>"
        + "<w:t xml:space=\"preserve\">Bold at 12 pt. </w:t></w:r>"
        + "<w:r><w:t>Plain run after it.</w:t></w:r></w:p>"
        + "<w:p><w:r><w:t>Third paragraph.</w:t></w:r></w:p>"
        + "<w:sectPr>"
        + "<w:pgSz w:w=\"12240\" w:h=\"15840\"/>"
        + "<w:pgMar w:top=\"1440\" w:right=\"1440\" w:bottom=\"1440\" w:left=\"1440\" "
        + "w:header=\"720\" w:footer=\"720\" w:gutter=\"0\"/>"
        + "</w:sectPr>"
        + "</w:body></w:document>"

    static func decode(_ base64: String) -> [UInt8] {
        guard let data = Data(base64Encoded: base64) else {
            fatalError("embedded fixture is not valid base64")
        }
        return [UInt8](data)
    }
}
